### ISSUE TITLE
Manually expand Accordion Item

### ISSUE THREAD

**Issue by wawhal** [daviferreira/react-sanfona#126] opened 2017-10-21 20:19 UTC
Is there a way to manually expand an Accordion item?
I am actually using redux. And I tried doing something like
```
<AccordionItem expanded={someBoolean} onExpand={expandingCallback}>
   {categorisedArray}
</AccordionItem>
```
where someBoolean comes from the redux state.

Now when I click one of the elements from categorised array, the accordion item gets closed even though the value of `someBoolean` is true in the state. **My goal is to preserve the state of the accordion i.e. before clicking an element from the array, if an accordion was opened, I want it to stay opened after the page re renders.**

I am trying to find a function or some tag that will help me to manually expand the accordion on receiving the props. Something like `this.showItem()`. Or any other way of achieving the main purpose will do too.

Thanks.

**Comment by daviferreira** [comment] 2017-10-22 08:39
Duplicate of #95

**Closed by daviferreira** 2017-10-22 08:39 UTC
